name: Rebuild battle dataset
on:
  schedule:
    - cron: '0 4 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: pip install feedparser geopy
      - name: Rebuild JSON
        run: python fetch_feed.py
      - name: Commit & push
        run: |
          git config --global user.email "bot@hgb-map"
          git config --global user.name "Map-Bot"
          git commit -am "auto: refresh battles.json" || echo "no changes"
          git push
